#!/usr/bin/env perl

use common::sense;
use FindBin;
use lib "$FindBin::Bin/../lib";
use SolveWith::Schema;
use SolveWith::Spreadsheet;
use Mail::SendEasy;
use Fcntl qw(:flock);
use App::Daemon qw(daemonize);

my $puzzle_id = shift;

$App::Daemon::logfile    = $FindBin::Bin . "/../log/give-puzzle-ss.log";
$App::Daemon::pidfile    = $FindBin::Bin . "/give-puzzle-ss-$puzzle_id.pid";
daemonize();

my $lock = $FindBin::Bin . '/do-google-docs-stuff.lock';
my $lock_fh;
open ($lock_fh, ">>", $lock) || die "Can't open $lock";
my $sleep = 1;
while (1) {
    if (flock($lock_fh, (LOCK_EX|LOCK_NB) )) {
        last;
    } else {
        warn "$$ Can't lock $lock for puzzle $puzzle_id\n";
        sleep $sleep;
    }
}
warn "$$ Got lock for puzzle $puzzle_id\n";

my $schema = SolveWith::Schema->connect('dbi:SQLite:' . $FindBin::Bin . '/../db/puzzles.db');
my $puzzle = $schema->resultset('Puzzle')->find($puzzle_id) || die "No puzzle found";

my $url = $puzzle->spreadsheet_peek;
if ($url) {
    print "$$ puzzle $puzzle_id has SS already\n";
    exit 0;
} else {
    eval {
        $url = SolveWith::Spreadsheet::puzzle_spreadsheet($puzzle);
    };
}

if ($url) {
    if (not $puzzle->spreadsheet_peek) {
        $puzzle->spreadsheet($url);
    }
} else {
    my $mail = new Mail::SendEasy( smtp => 'localhost' );
    my $status = $mail->send(
        from    => '***REMOVED***' ,
        from_title => 'Solvewith.us Spreadsheet Creation Script' ,
        to      => 'ecp@prestemon.com' ,
        subject => $puzzle->display_name . " SS creation failed" ,
        msg     => "I could not create the SS for puzzle id $puzzle_id\n$@\n" ,
    ) ;
    print "$$ Email status: $status\n";
    exit 1;
}
print "$$ $url\n";
exit 0;


