#!/usr/bin/env perl

use common::sense;
use FindBin;
use lib "$FindBin::Bin/../lib";
use SolveWith::Schema;

my $team_id = shift;

my $schema = SolveWith::Schema->connect('dbi:SQLite:' . $FindBin::Bin . '/../db/puzzles.db');
my $team = $schema->resultset('Team')->find($team_id);
die unless $team;

my $url = SolveWith::Spreadsheet::team_auth_spreadsheet($team->google_group);
if ($url) {
    $team->chat->messages->search({type => 'spreadsheet'})->delete;
    $team->chat->set_spreadsheet($url);
    warn $team->chat->get_spreadsheet;
}

my $share_folder = SolveWith::Spreadsheet::team_folder($team->{google_group});
if ($share_folder) {
    $team->chat->set_folder($share_folder->alternate);
    warn $team->chat->get_folder;
}

