#!/usr/bin/env perl
use 5.012;
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'SolveWith';

# Start commands
if (Mojolicious::Commands->can('start_app')) {
    Mojolicious::Commands->start_app($ENV{MOJO_APP});
} else {
    Mojolicious::Commands->start;
}
