#!/usr/bin/env perl

use common::sense;
use FindBin;
use lib "$FindBin::Bin/../lib";
use SolveWith::Schema;
use Mojo::Server;
use Time::HiRes;

$ENV{MOJO_MODE} = 'production';
my $server = Mojo::Server->new;
my $app = $server->load_app($FindBin::Bin . '/solve_with');
$app->mode('production');

my $schema = SolveWith::Schema->connect('dbi:SQLite:' . $FindBin::Bin . '/../db/puzzles.db');

for my $message ($schema->resultset('Message')->all) {
    $message->chat->maybe_add_puzzle_info($message->type, $message->text, $message->user_id, $message);
}

